### ISSUE TITLE
Tabs not working anymore with latest foundation release. 

### ISSUE THREAD

**Issue by ro8in** [circlingthesun/angular-foundation-6#43] opened 2017-02-08 13:43 UTC
With Foundation 6.3.0 the TABS are not working anymore. Tabs are showing, but the content of the tab is not. 

Had to revert back to the CSS from 6.2.4

**Comment by circlingthesun** [comment] 2017-02-09 20:28
It has not been tested with 6.3 yet.

**Comment by MrNuTruT** [comment] 2017-02-09 21:29
yes i have the same problem

**Comment by mamos98** [comment] 2017-02-15 08:47
@circlingthesun The problem is that foundation uses the CSS code below or should I say `aria-hidden="false"` to check if a tab's content should be seen or not in the latest version! But in `v6.2.x` it used `.is-active` class along with `.tab-panel` to show tabs content! I donno if this is a good approach or not or why did they do this. I liked the old approach of doing this.
```css
.tabs-panel[aria-hidden="false"] {
    display: block;
}
```

**Comment by circlingthesun** [comment] 2017-02-15 08:59
@mamos98, thanks for pointing that out. This project aims to be compatible with foundation for sites without external css. So the code will have to be updated. Personally, I see no real benefit in moving to 6.3.0 at this stage. I'm not opposed to upgrading, I just don't have the time right now. I'm open to PRs though :)

**Comment by mamos98** [comment] 2017-02-15 09:33
@christopherthielen I would love to. But I also agree that most of the people are still using the version `6.2.x`. I downgraded to `6.2.x` myself. I'll work on it once I get the chance!

**Comment by circlingthesun** [comment] 2017-08-29 21:58
Fixed in #59

**Closed by circlingthesun** 2017-08-29 21:58 UTC
